# Generated by Django 4.1.3 on 2023-01-03 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_ID', models.CharField(max_length=1000)),
                ('room_ID', models.CharField(max_length=3)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('floor', models.IntegerField(max_length=3)),
                ('name', models.CharField(max_length=100)),
                ('clean_status', models.CharField(max_length=1)),
            ],
        ),
    ]
