# Generated by Django 4.1.3 on 2023-01-03 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotelapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='reservations',
            table='Reservations',
        ),
        migrations.AlterModelTable(
            name='rooms',
            table='Rooms',
        ),
    ]
